server:
  port: 8083


spring:
  application:
    name: auth-service
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update
        show-sql: true
  datasource:
    username: ${database.user:postgres}
    password: ${database.password:sanjay}
    url: ${database.url:jdbc:postgresql://localhost:5432/auth-service?createDatabaseIfNotExist=true}


    initialization-mode: always
    initialize: true
    schema: classpath:/schema.sql
    continue-on-error: true

eureka:
  instance:
    prefer-ip-address: true

  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    enabled: true
management:
  endpoint:
    serviceregistry:
      enabled: true
    web:
      exposure:
        include: "*"
rest:
  swagger:
    enabled: true

jwt:
  signing-Key: va6w3Fr1goCcrues0p//sanjay/tL

