server:
  port: 8083


spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:mysql://localhost:3306/auth_service
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
      # Keep the connection alive if idle for a long time (needed in production)
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect


eureka:
  instance:
    prefer-ip-address: true

  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
rest:
  swagger:
    enabled: true

jwt:
  signing-Key: va6w3Fr1go//sanjay/umasanjayvishwa
